# Generated by Django 5.0 on 2023-12-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('regNo', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=13)),
            ],
        ),
        migrations.DeleteModel(
            name='CRUD',
        ),
    ]
